### ISSUE TITLE
vs 2017

### ISSUE THREAD

**Issue by papyr** [renegadexx/T4.Helper#12]
Hi will this work  in 2017

**Comment by renegadexx** [comment]
Currently I test the FileManager and implement the suggestion of issue 10 for debugging T4 stuff in Visual Studio.

For .NET Standard Projects I must refactor the NuGet Package.

The new version will be 3.0

**Comment by TSSchoof** [comment]
Hi there,

This doesn't seem to work in Visual Studio 2017. I get an exception on the Microsoft.VisualStudio.Shell.10.0 not being found. Any ideas?

Thanks

**Comment by Vijay-Nirmal** [comment]
> It seems like Visual Studio doesn't automatically register:
> - Microsoft.VisualStudio.Shell.10.0.dll
> - Microsoft.VisualStudio.Shell.Interop.dll

@TSSchoof @renegadexx Any update on this?

**Comment by Eagle3386** [comment]
Sorry for being late to the party, but for anyone still caring, here's a list of required changes to get it working with VS 2019:

1. Update your reference to `Microsoft.VisualStudio.Shell.15.0`.
2. Add additional reference to `Microsoft.VisualStudio.Shell.Framework`
3. Add `<#@ assembly name="Microsoft.VisualStudio.Shell.Framework" #>` to the `TemplateFileManager.ttinclude` file.

Afterwards, everything should work as expected.

**Comment by papyr** [comment]
This is very handy, can we get intellisense or a list of keyword we can add to the helper to do some customization. The one from Tangible is broken. and not free.

**Comment by Eagle3386** [comment]
If you're using ReSharper, I highly recommend to install the [ForTea extension](https://github.com/jetbrains/fortea/).
Other than I only know of DevArt's [T4 Editor](https://www.devart.com/t4-editor/) which is free.
