### ISSUE TITLE
Project still maintained

### ISSUE THREAD

**Issue by stefantinger** [renegadexx/T4.Helper#19]
Will this project still be maintained? Last submits were 2 years ago, pull requests open since march...

**Comment by Epsilekt** [comment]
There are a few tricks that make this manager file unneeded. Look at my TexTran repositories, where I transform T4 Templates that generate separate files in multiple separate folders. 1 line code can prevent ouput in child node and another line writes them to custom file/folders.

**Comment by databinding-thierryiseli** [comment]
Maybe some interesting information for you. We have worked out a new FileManager, which can also be used in .NET Core project: https://github.com/databinding-gmbh/T4.FileManager.VisualStudio. Currently, only the documentation is on GitHub. The code will follow.

**Comment by databinding-thierryiseli** [comment]
The entire code is now on GitHub and includes some user story oriented SpecFlow testing: https://github.com/databinding-gmbh/T4.FileManager.VisualStudio.
