### ISSUE TITLE
Remove trailing spaces

### ISSUE THREAD

**Issue by MagicAndre1981** [renegadexx/T4.Helper#6]
Please remove the annoying trailing spaces. 

You can see them with this extension (https://visualstudiogallery.msdn.microsoft.com/a204e29b-1778-4dae-affd-209bea658a59)

![Trailing Spacet](https://dl.dropboxusercontent.com/u/5749744/Bilder/Github/T4_Template_TrailingSpace.png)

**Comment by renegadexx** [comment]
Removed with version 2.2.1

**Comment by MagicAndre1981** [comment]
thanks :) Btw, here is an extension to automatically remove them on save: 

https://github.com/ideaconnect/vs-trim-line-ends-on-save-plugin
