### ISSUE TITLE
Specifying BuildAction does not work

### ISSUE THREAD

**Issue by tehplague** [renegadexx/T4.Helper#7]
I am trying to generate C# code for a separate project using a T4 template that should not be built in the current project and should therefore be included as static content. My template uses

```
manager.StartNewFile(endpointClassName + ".cs", fileProperties: new FileProperties()
{
    BuildAction = BuildAction.Content
});
```

to start a new file. However, the VS project file properties list `Compile` as the selected build action and the project file's XML contains `<Compile>` tags.

How is it possible to force TemplateFileManager into setting the build action properly? It obviously ignores the `fileProperties` parameter which I consider a bug.

**Comment by renegadexx** [comment]
Hi

I can´t reproduce the behavior. Do you have "manager.CanOverwriteExistingFile" set to true?

Which version of visual studio do you use?
